services:
  - type: web
    name: gng-agent
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir --prefer-binary --no-build-isolation -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_TABLE_NAME
        value: "Verified Athletes"
